### ISSUE TITLE
Alterar e-mail do mantenedor do projeto

### ISSUE THREAD

**Issue by alvesmgabriel** [floripasat/fsat-decoder#5]
Solicito, por gentileza, retirar o meu e-mail do código do projeto e substituí-lo para o endereço correto.
Obrigado.

Referência:
https://github.com/floripasat/fsat-decoder/blob/208072da8b19dd4e93c78e3ec1c02352d9b4ee0d/fsat-decoder/__init__.py#L29

**Comment by mgm8** [comment]
@alvesmgabriel isso já havia sido corrigio neste commit: https://github.com/floripasat/fsat-decoder/commit/ba614ac108baf337e0eec29398ec6c14dceedfa5, mas ele ainda estava na branch dev. Já fiz o merge e agora não há mais referências ao seu e-mail.

Desculpe pelo engano, nossos nomes são parecidos. Acabei trocando o username do gmail com uma contra que tenho em outro serviço.

**Comment by alvesmgabriel** [comment]
@mgm8 agradeço pela correção. Eu soube desse engano, pois uma pessoa entrou em contato querendo informações a respeito do projeto. Eu passei o seu e-mail para ela, mas se preferir posso lhe encaminhar as mensagens. Obrigado.

**Comment by mgm8** [comment]
@alvesmgabriel a pessoa já entrou em contato, obrigado.
